### ISSUE TITLE
Doesn't seem to work on Xcode 12.5 simulator unless "Excluded architectures" is configured

### ISSUE THREAD

**Issue by darthdeus** [Gordon-F/miniquad_ios_example#2]
I'm not sure what exactly is causing this, but I needed to make this change for it to work in a simulator on Xcode 12.5

![](https://i.stack.imgur.com/SEYAV.png)

Without it I get the following error

```
ld: in ../target/universal/debug/libminiquad_ios_example.a(miniquad_ios_example-9052c3584552a0ca.4gnktxao9t3bu45t.rcgu.o), building for iOS Simulator, but linking in object file built for iOS, for architecture arm64
```

**Comment by Gordon-F** [comment]
Unfortunately `cargo-lipo` is deprecated and doesn't work on new Apple processors. This example needs to be updated. PR would be really appreciated! See https://github.com/bevyengine/bevy/pull/3109 as a reference.
